title: "Rodrigo Véliz Estrada"
name: "Rodrigo Véliz Estrada"
description: "Historian | Research Fellow | Freie Universität Berlin"
site_theme: "air_light"
url: "https://rvelizestrada.github.io"
repository: "rvelizestrada/rvelizestrada.github.io"

author:
  name: "Rodrigo Véliz Estrada"
  avatar: "/images/bio-photo.jpg"
  bio: "Alexander von Humboldt Research Fellow at the Lateinamerika-Institut, Freie Universität Berlin. Historian specialising in the 20th-century Cold War in the Caribbean Basin."
  location: "Berlin, Germany"
  employer: "Freie Universität Berlin"
  email: "rveliz@zedat.fu-berlin.de"
  uri:
  googlescholar:
  orcid: "https://orcid.org/0000-0002-6140-1436"
  twitter: "rorito_rve"
  github: "rvelizestrada"
  researchgate: "https://www.researchgate.net/profile/Rodrigo_Veliz_Estrada"

locale: "en-US"
timezone: Europe/Berlin

include:
  - .htaccess
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

markdown: kramdown
highlighter: rouge
